### ISSUE TITLE
Viewing orbits in Cesium error due to incorrect CZML file created.

### ISSUE THREAD

**Issue by aashayshahh** [kujosHeist/tle2czml#3]
Hello,
I used tle2czml to create CZML files from the TLE data that I have for a particular satellite. The CZML file gets created without an issue. But when I use that file in Cesium Viewer to have a look at the orbit - it throws me an error saying that CZML file has unexpected token. I inspected the CZML file and I believe the error arose because of NaN values at some places.

Details on my version -
Python 3.7
tle2czml 0.1

Is there any way I can fix this issue? Do I need to make changes in the python file of tle2czml anywhere?

Traceback of the error looks like: 
```
An error occurred while loading the file: test.czml
An error occurred while loading the file, which may indicate that it is invalid.  A detailed error report is below:

SyntaxError: Unexpected token N in JSON at position 28171
SyntaxError: Unexpected token N in JSON at position 28171
    at JSON.parse (<anonymous>)
    at FileReader.<anonymous> (https://cesiumjs.org/Cesium/Build/Apps/CesiumViewer/CesiumViewerStartup.js:522:13213)
```

**Comment by kujosHeist** [comment]
Hi aashayshahh,

Sorry for delay!

I think this is caused by the TLE's being too old.
So when you try to generate the CZML for now, using the TLE's from 2018, it gives a NaN for some values.

If you update the TLE's (for example from here https://www.celestrak.com/NORAD/elements/stations.txt) it should work for you

Thanks
